### ISSUE TITLE
create breadcrumb

### ISSUE THREAD

**Issue by mklmotors** [cleonixtechnologies/MKL-Motors#10]
please create a breadcrump on all of the mkl ford transit engine pages:

www.mklfordtransitengines.co.uk

just like the ones visible here:

http://www.mklmotors.com/reconditioned-engines/

**Comment by bikash02** [comment]
updated the breadcrump

**Comment by mklmotors** [comment]
thanks bikash.

Please kindly create this breadcrumb for all the new sites now please

**Comment by bikash02** [comment]
updated all the websites.

**Comment by mklmotors** [comment]
excellent work bikash
