### ISSUE TITLE
mklfordtransitengines.co.uk - new pages

### ISSUE THREAD

**Issue by mklmotors** [cleonixtechnologies/MKL-Motors#12]
As per discussion with debdip, we need to create a series of new pages for seo purposes.

Ford Transit Engines                                mk5        mk6        mk7          mk8
Reconditioned Ford Transit Engines      reconditioning   |    recon  |  rebuild 
Used Ford Transit Engines                       replacement    |  2nd hand  | second hand |  van
Ford Transit Connect Engines  
Ford Transit 2.4 Engines  
Ford Transit 2.2 Engines  
Ford Transit Diesel Engines                     tdci    |   duratorq  |  rwd   |   fwd
Ford Transit Tourneo Engines  
Ford Transit 1.8 Engines  
Ford Transit 350 Engines    

Each of the above pages should have an additional two links:

1) Ford Transit Engines by year
2) Ford Transit Engines by location

**Comment by bikash02** [comment]
Please check the below link 
http://www.mklmotors.com/mklfordtransitengines/ford-transit-mk5-engines/
If the design is okay then we will go for the next pages..

**Comment by mklmotors** [comment]
perfect, please proceed

**Comment by debdiproy** [comment]
Reconditioned Ford Transit Engines reconditioning | recon | rebuild 
1. Ford Transit Engines Reconditioning
2. Recon Ford Transit Engines
3. Ford Transit Engine Rebuild

**Comment by mklmotors** [comment]
Used Ford Transit Engines replacement | 2nd hand | second hand | van
1. Replacement Ford Transit Engines
2. 2nd Hand Ford Transit Engines
3. Second Hand Ford Transit Engines
4. Ford Transit Van Engines

**Comment by mklmotors** [comment]
Ford Transit Diesel Engines tdci | duratorq | rwd | fwd
1. Ford Transit tdci Engines
2. Ford Transit Duratorq Engines
3. Ford Transit rwd Engines
4. Ford Transit fwd Engines

**Comment by bikash02** [comment]
Pages are created.

**Comment by mklmotors** [comment]
what is the status on this please?

**Comment by bikash02** [comment]
Kindly check the below link
http://mklfordtransitengines.co.uk/
Please let me know if anything else need to be updated on this section.

**Comment by mklmotors** [comment]
thats all been done incorrectly im afraid.

the product categories section on the homepage should have:
- Reconditioned Ford Transit Engines
- Used Ford Transit Engines
- Ford Transit mk5 Engines
- Ford Transit mk6 Engines
- Ford Transit mk7 Engines
- Ford Transit mk8 Engines

The sub categories for the reconditioned ford transit engines page, used ford transit engines page and ford transit diesel engines page, should only appear once you navigate to their respective page. They shouldnt appear on the homepage. 

I hope that is clear. If you need further clarification please dont hesitate to get in touch

**Comment by bikash02** [comment]
Kindly check the below links.
http://www.mklfordtransitengines.co.uk/
http://www.mklfordtransitengines.co.uk/used-ford-transit-engines/
http://www.mklfordtransitengines.co.uk/ford-transit-mk6-engines/
http://www.mklfordtransitengines.co.uk/ford-transit-diesel-engines/

**Comment by debdiproy** [comment]
By year
2000 ford transit 2.2 engine
2001 ford transit 2.2 engine

By location
ford transit 2.2 engines in Aberdeen
ford transit 2.2 engines in Bath

**Comment by bikash02** [comment]
We have added the pages for ford transit diesel engines
http://www.mklfordtransitengines.co.uk/ford-transit-diesel-engines/
Let me know if anything else you need to be updated.

**Comment by mklmotors** [comment]
hi bikash, thank you for adding that. Just a couple of things to fix please.

when you go to ford transit diesel engines by year, each one should be in a sub category.

for example at the moment if you select "2000 Ford Transit Diesel Engines"

the link address is:

http://www.mklfordtransitengines.co.uk/2000-ford-transit-diesel-engines/

but ""2000 Ford Transit Diesel Engines" is a sub category of "ford transit diesel engines"

so the web address for it should be:

http://www.mklfordtransitengines.co.uk/ford-transit-diesel-engines/2000-ford-transit-diesel-engines/

and the same should be reflected in the breadcrumb for each page. please also apply the same for the by location categories.

Also, some of the by location titles on the menu on the left carry on to the 2nd line as you can see from the following link:

http://www.mklfordtransitengines.co.uk/ford-transit-engines-by-location?st=ford-transit-diesel-engines

please make them all on the same line, even if you have to reduce the text box on the right. 

please let me know if you have any questions

**Comment by bikash02** [comment]
We have updated the pages.

**Comment by bikash02** [comment]
We are working on the next engine and will update you after some time..

**Comment by bikash02** [comment]
Added all the pages for "Ford Transit 2.2 Engines" .Please check the link.
http://www.mklfordtransitengines.co.uk/ford-transit-2-2-engines/

**Comment by bikash02** [comment]
We have added the year and location pages for the below engines.

Ford Transit Diesel Engines
Ford Transit 2.2 Engines  
Ford Transit 2.4 Engines 
Ford Transit Connect Engines
Ford Transit Tourneo Engines 
Ford Transit 350 Engines

Ford Transit mk5 Engines
Ford Transit mk6 Engines
Ford Transit mk7 Engines
Ford Transit mk8 Engines

Let me know if anything else you need.
