### ISSUE TITLE
mobile optimisation

### ISSUE THREAD

**Issue by mklmotors** [cleonixtechnologies/MKL-Motors#13]
when viewing the site from a mobile device, the logo that appears at the top is far too big. Please significantly reduce the size of it, move it to the top left and have the menu button with the 3 lines alongside it.

also, the option to "log in" or "create an account" should be added to the menu and not appear separately.

Also, the following page needs to be correctly mobile optimised:

http://www.mklmotors.com/reconditioned-engines/

**Comment by mklmotors** [comment]
what is the status on this please?

**Comment by bikash02** [comment]
We will update you on Monday.

**Comment by Designer-cleonix** [comment]
Update the header portion. and working on the following issue
" Also, the following page needs to be correctly mobile optimised:
http://www.mklmotors.com/reconditioned-engines/"

**Comment by mklmotors** [comment]
this is now complete, good work
