### ISSUE TITLE
review system

### ISSUE THREAD

**Issue by mklmotors** [cleonixtechnologies/MKL-Motors#14]
the review system needs to be fixed as it is reflecting a number of issues when you try to submit a review by creating an account.

Once you enter your review and the rating, and you go to submit it, it prompts you to create an account, after your account is created, all the review you wrote is lost and you have to re-submit it again. Please correct this issue.

**Comment by bikash02** [comment]
It's a third party plug-in.So we can't alter the plug-in code and if somehow we manage it,the code will not work after the plug-in or word press is updated..

**Comment by mklmotors** [comment]
so what is the solution? as currently its preventing our clients from entering reviews effectively.

**Comment by bikash02** [comment]
We get a solution for the issue.
Now if the clients want to write a review they have to login or create a account first and then able to write a review. http://www.mklmotors.com/reviews/

Let me know it is okay or not.

**Comment by mklmotors** [comment]
thats a clever a idea

but what if the client wants to submit their review using a social media account?

**Comment by mklmotors** [comment]
i think this is now resolved, good work
