### ISSUE TITLE
new parts templates

### ISSUE THREAD

**Issue by mklmotors** [cleonixtechnologies/MKL-Motors#16]
Hi debdip, 

as per our conversation, I i need the following templates. Please dont worry about the content, I will take care of all them:
- Gearboxes (already there, just change details in subject box) = GEARBOX DATA:
- Cylinder heads - subject box = C.HEAD DATA:
- Clutch - subject box = CLUTCH DATA:
- Brake Pads - subject box = BRAKE PADS DATA:

There will be more to come.

Kind Regards

Khaled

**Comment by debdiproy** [comment]
Here are the pages to check from:

http://www.mklmotors.com/gear-box/
http://www.mklmotors.com/cylinder-heads/
http://www.mklmotors.com/clutch/
http://www.mklmotors.com/brake-pads/

**Comment by mklmotors** [comment]
excellent work debdip,

just kindly correct the formatting of the text in the thank you page please

http://www.mklmotors.com/thank/

**Comment by mklmotors** [comment]
please redirect all turbocharger, maf sensor, egr valve, and fuel pump pages to the standard vrm search data as above. We have now discontinued the parts service

**Comment by bikash02** [comment]
Updated turbocharger, maf sensor, egr valve, and fuel pump pages and  the  thank you page also..

**Comment by mklmotors** [comment]
this is now complete, good work guys
