### ISSUE TITLE
new bmw pages created

### ISSUE THREAD

**Issue by mklmotors** [cleonixtechnologies/MKL-Motors#17]
the new bmw pages created require some small fixes. 

1) The two tags created in the body of the text are not formatted well and should have one line of space above and also one line of space below.

For example in:

http://www.mklmotors.com/reconditioned-engine/reconditioned-bmw-525d-engines-sale/

"Reconditioned Reconditioned BMW 525d Engines For Sale     Used Reconditioned BMW 525d Engines For Sale "

2) The data in the vehicle overview section needs to be changed a bit.
- Production: 1916 = present
- Body style = various
- Predecessor = various
- Engines = (please use the codes from the attached excel spreadsheet, put the codes into two columns side by side so that they dont take up too much space)

3) please create bmw engine pages by year e.g.
- 2005 BMW engines
- 2006 BMW engines
  ......
  until 
- 2016 BMW engines

**Comment by bikash02** [comment]
Updated the first issue.Please check from yourend.

**Comment by mklmotors** [comment]
unfortunately that hasnt been done properly Bikash. Compare it to this one:

http://www.mklmotors.com/reconditioned-engine/reconditioned-range-rover-2-7-engines-sale/

**Comment by bikash02** [comment]
Sorry it was my mistake.I did only for BMW page template.
Please check once again.
Thank you.

**Comment by mklmotors** [comment]
sorry but i didnt want it like the bmw one, i wanted it to be like the range rover one which was the one i did myself. The text was a purple colour and underlined. please change it back to that one and make them all like that.

**Comment by bikash02** [comment]
updated the range rover template.

**Comment by mklmotors** [comment]
now please make all the bmw templates the same as this one

**Comment by bikash02** [comment]
updated the bmw templates.

**Comment by bikash02** [comment]
I didn't find any attached file for engines code.Can you please provide me the file?

**Comment by mklmotors** [comment]
[bmw engine codes.xlsx](https://github.com/cleonixtechnologies/MKL-Motors/files/281943/bmw.engine.codes.xlsx)

**Comment by mklmotors** [comment]
I have just attached it

**Comment by bikash02** [comment]
Thank you @mklmotors .
We are changing on the vehicle overview section and will update you by tomorrow.

**Comment by bikash02** [comment]
updated the BMW vehicle overview section.

**Comment by debdiproy** [comment]
3) please create bmw engine pages by year e.g.

```
2005 BMW engines
2006 BMW engines ...... until
2016 BMW engines
```

Please let me know if this will be on the mklmotors.com domain or the mklbmwengines domain

**Comment by mklmotors** [comment]
please create these on the mklmotors.com domain, the same as the other pages

**Comment by bikash02** [comment]
Added bmw engine pages by year.

**Comment by mklmotors** [comment]
thank you. please update the excel spreadsheet of the list of created pages and email it to me within the next 2 hours. thank you

**Comment by debdiproy** [comment]
Excel sheet emailed by year please check
