### ISSUE TITLE
create Job Log

### ISSUE THREAD

**Issue by mklmotors** [cleonixtechnologies/MKL-Motors#4]
To create a separate blog section which will be called "Job Log" which will have a tab at the top of the head together with the other tabs. This will be specifically for logging completed jobs only.

**Comment by bikash02** [comment]
added the "Job Log" section.

**Comment by mklmotors** [comment]
thanks for creating the job log.

however the structure of the job log and formatting style should be identical to the blog. please kindly make the necessary changes

**Comment by bikash02** [comment]
updated the design.
please let me know if anything else you need

**Comment by mklmotors** [comment]
thank you. the posts in the job log and the blog should be completely different sections. so the recent posts and recent comments from one section should not be reflected in the other and vice versa. please apply the necessary change.

**Comment by bikash02** [comment]
updated the job log and the blog section.

**Comment by mklmotors** [comment]
urgently address the blog section!!

all the previous posts have been heavily distorted. please fix this as a matter of urgency. also make sure you test the job log section for the same issues.

**Comment by mklmotors** [comment]
as per discussion with debdip please copy the exact features of the following blog section to our own:

http://crossfitthames.com/blog/

please apply them to both the blog section and job log section

**Comment by mklmotors** [comment]
please also move all the posts we created for jobs completed from the blog section and put them into the job log section

**Comment by Designer-cleonix** [comment]
Moved the following posts to job log section.
- Range Rover Sport 3.6 TDV8 Engine Replacement
- Mercedes C250 2.2 diesel Engine Replacement for Mr Fisher
- BMW 520d Engine Replacement and Fitting
- BMW 525D 3.0 Diesel Engine replacement and fitting
- Citroen Dispatched 2012 2.0 Diesel Engine Replacement and Fitting
- BMW X6 Engine Replacement and Installation for Mr Smith
