### ISSUE TITLE
sitemap indexing issue

### ISSUE THREAD

**Issue by mklmotors** [cleonixtechnologies/MKL-Motors#5]
currently only 2021 pages are being indexed with sitemap. There should be more than double this amount. It is also showing 1800 broken links.

**Comment by debdiproy** [comment]
Hello Khaled as per our conversation i have verified your sites and sitemaps please unsubscribe to the third party service. Sagar is doing a complete analysis of all the site maps and he will update you with a comment here.

**Comment by mklmotors** [comment]
i have emailed sitemap and arranged to cancel the account.

this issue is now resolved
