### ISSUE TITLE
video testimonial playlist

### ISSUE THREAD

**Issue by mklmotors** [cleonixtechnologies/MKL-Motors#6]
the video playlist which is embedded in a number of locations doesnt automatically update when a new video is uploaded to youtube. Please kindly fix this and ensure that it is not for all the different sections/websites where the video testimonials section is present

**Comment by bikash02** [comment]
@mklmotors  Please provide us  your YouTube API key for integrating the video functionality.

**Comment by mklmotors** [comment]
is there any update on this please?

**Comment by bikash02** [comment]
We are working on the youtube api and will update you by tomorrow.

**Comment by bikash02** [comment]
I have integrated the API in the mklmotors.com and the rest of the websites as well.Kindly check and let me know your feedback.

**Comment by mklmotors** [comment]
thank you Bikash. there are now 4 videos which appear below the main featured video which is fine. However, this should be the limit and if there are any more videos added then it should turn into a cascading style where you can scroll from left to right to view all the videos

**Comment by mklmotors** [comment]
I have just checked the video testimonials sections on the others websites and it is not showing up at all. It only appears to work correctly on mklmotors.com

**Comment by bikash02** [comment]
The youtube api is working fine for the http://www.mklmotors.com/mklfordtransitengines/
but not working for http://www.mklfordtransitengines.co.uk/

Its happens due to domain name because the youtube app is domain dependent and we created the app only for the mklmotors.com.So either we have to create the individual app for the domains or websites or else find a alternative solution.

**Comment by bikash02** [comment]
I have resolved the issue using a single app.Kindly check and give me your feedback.
please add a test video in your youtube channel and check that it was added to website playlist or not.
Waiting for your reply..

**Comment by mklmotors** [comment]
I have added another video and it has automatically loaded onto the sites. 

Excellent work Bikash, well done!
