### ISSUE TITLE
account registration and login

### ISSUE THREAD

**Issue by mklmotors** [cleonixtechnologies/MKL-Motors#7]
When creating an account, a user should be requested to enter a password and confirm it (two separate boxes).

Once a user is logged in, his logged in status should be reflected on the top right of the website, with an option to log out.

**Comment by mklmotors** [comment]
update on this please

**Comment by bikash02** [comment]
I have updated the section.Kindly check and give us your review.

**Comment by bikash02** [comment]
I updated only for the main website.What to do for the rest of the websites?

**Comment by mklmotors** [comment]
thats fine. the main site is what is most important, thanks bikash
