### ISSUE TITLE
blog and job log issue

### ISSUE THREAD

**Issue by mklmotors** [cleonixtechnologies/MKL-Motors#8]
The styling of the blog and job log section is now fine. However, once someone clicks on an individual post, the styling of the page then completely changes to a different format. see below:

http://www.mklmotors.com/blog/2016/02/01/3-major-signs-engine-trouble/

Please address this and make the styling of the individual posts to be the same as the blog and job log

**Comment by bikash02** [comment]
resolved the issue

**Comment by mklmotors** [comment]
thank you Bikash. Please add the sharing section as well the correct styling for the "leave a comment" just like in the blog and job log section

**Comment by bikash02** [comment]
@Designer-cleonix please update the design part asap.

**Comment by mklmotors** [comment]
update on this please

**Comment by Designer-cleonix** [comment]
Updated.

**Comment by mklmotors** [comment]
yes this has now been completed, well done guys
